const STEPS = [
  {
    step: "01",
    title: "Send two photos",
    body: "One from inside showing floor to ceiling, one from outside showing the wall. That is all the scale we need.",
  },
  {
    step: "02",
    title: "Confirm the size",
    body: "We read the opening against your ceiling height or the brick coursing, then show you the number and ask if it looks right.",
  },
  {
    step: "03",
    title: "Answer three questions",
    body: "Which floor, what broke, and whether it is near a door or a bath — the things that decide equipment and safety glazing.",
  },
  {
    step: "04",
    title: "A person prices and sends",
    body: "A glazier checks the details, prices the job from our rate book and sends the estimate — usually the same day.",
  },
] as const;

export function HowItWorksSection() {
  return (
    <section className="mx-auto max-w-[74rem] px-6 py-20 lg:py-[5.5rem]">
      <div className="mb-13 flex max-w-[38.75rem] flex-col gap-4">
        <span className="text-accent-500 text-xs font-semibold tracking-[0.12em] uppercase">
          How it works
        </span>
        <h2 className="font-display text-brand-950 text-[2rem] leading-[1.15] font-bold tracking-[-0.022em] sm:text-[2.375rem]">
          The assistant collects. A glazier prices.
        </h2>
        <p className="text-[17px] leading-7 text-slate-600">
          Nothing is quoted automatically, and no price is ever generated by
          software. That is deliberate — our name goes on the number.
        </p>
      </div>

      <ol className="border-border-subtle grid border-t sm:grid-cols-2 lg:grid-cols-4">
        {STEPS.map(({ step, title, body }, index) => (
          <li
            key={step}
            className={`border-border-subtle flex flex-col gap-3.5 pt-8 sm:pr-7 ${
              index === STEPS.length - 1 ? "" : "lg:border-r"
            } ${index > 0 ? "lg:pl-7" : ""}`}
          >
            <span className="text-accent-500 font-mono text-[13px] font-medium tracking-[0.06em]">
              {step}
            </span>
            <p className="font-display text-brand-950 text-[19px] font-semibold tracking-[-0.01em]">
              {title}
            </p>
            <p className="text-[15px] leading-[25px] text-slate-600">{body}</p>
          </li>
        ))}
      </ol>
    </section>
  );
}
